apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubarr-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.serviceName }}.{{ .Values.database.namespace }}.svc.cluster.local:5432/{{ .Values.database.name }}"
