apiVersion: v1
kind: Secret
metadata:
  name: kubarr-db-app
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@kubarr-db-rw.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/{{ .Values.database.name }}"
