apiVersion: v1
kind: Secret
metadata:
  name: kubarr-db-app
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@kubarr-db-rw.{{ .Values.namespace.name }}.svc.cluster.local:{{ .Values.service.port }}/{{ .Values.database.name }}"
