apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubarr-dns-webhook.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubarr-dns-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "kubarr-dns-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
