apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubarr-dns-webhook.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubarr-dns-webhook.labels" . | nindent 4 }}
